### ISSUE TITLE
Anlegen des ersten User schlägt (ohne Fehlermeldung!) fehl

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/teststudio-lite-backend#15]
Steps:
- Frische Installation
- Navigieren zum Tab nutzer und neuen Nutzer hinzufügen
-> Nichts passiert

Hier ein Auschnitt der Konsolenausgabe:
teststudio-lite-db          | ERROR:  duplicate key value violates unique constraint "pk_users"
teststudio-lite-db          | DETAIL:  Key (id)=(1) already exists.
teststudio-lite-db          | STATEMENT:  INSERT INTO users (name, password) VALUES ($1, $2)
teststudio-lite-backend     | localhost:80 192.168.7.4 - - [24/Mar/2021:11:15:10 +0000] "POST /php_superadmin/addUser.php HTTP/1.1" 200 939 "https://141.20.184.43/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"

**Comment by rhenck** [comment]
Das gleiche gilt für Workspaces.

**Comment by mechtelm** [comment]
Das sieht mir aus wie ein fehlerhaftes create-Script für die Datenbank. Die autoincrement-Funktion läuft nicht.
