### ISSUE TITLE
Beispielplayer/-editoren bereitstellen

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/teststudio-lite-backend#16]
Sonst geht keine Preview. Ich denke es wäre gut, wenn das trotdzem ginge.

Nachfolgend der Abschnitt aus einem alten entrypoint script, das Philipp mal angelegt hat. Das wird jetzt nicht mehr benutzt, enthält aber den entscheidenden Fix.

```
  echo "importing dan-player/player 2.1.0"
  cp /teststudio-lite-plugins/verona-player-dan/releases/2.1.0/unitPlayer/IQBVisualUnitPlayerV2.1.0.html \
    "$playersDir/IQBVisualUnitPlayerV2.html" # must be renamed, because teststudio-lite does not support sub-versions
```

**Comment by mechtelm** [comment]
Im Verzeichnis `verona-modules` sollten einige Player und Editoren liegen für den Start.

**Comment by rhenck** [comment]
> Im Verzeichnis `verona-modules` sollten einige Player und Editoren liegen für den Start.

Dann mach zu, wenn das erledigt ist. Afaik ist der branch aber noch nicht gemergt.

**Comment by mechtelm** [comment]
Es sollten keine Verona-Module in die Distribution gespielt werden. Jedem, der die Installation vornimmt, kann egal sein, was die Inhaltsleute für Player oder Editoren benötigen. Das muss dann der Superadmin einspielen je nach Bedarf. Wir müssten sonst ständig die neuen Versionen in die Distribution schieben, also nur weil der Dan-Player eine neue Version hat, soll das Teststudio-Setup neu gebaut werden? Nee!
