### ISSUE TITLE
Unique Key sicherstellen

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/teststudio-lite-backend#17]
Ein Key darf
* nicht leer sein
* muss eindeutig sein innerhalb eines Workspaces (whitespaces entfernen, klein/groß ignorieren)

Zu implentieren für
* addUnit
* changeUnitProperties
* unit-import

**Comment by svwolter** [comment]
Überarbeitung abgeschlossen, Anpassung des Frontends notwendig!

**Comment by svwolter** [comment]
moveUnits Endpoint liefert nun im Erfolgsfall ein leeres Array zurück und im Miss- bzw. Teilerfolgsfall nicht mehr den Errorcode 406, sondern ein array mit den nicht verschiebaren Units.
