### ISSUE TITLE
Import von Test-Units: Fehlersituation an User melden

### ISSUE THREAD

**Issue by svwolter** [iqb-berlin/teststudio-lite-backend#24]
Das Backend soll einen Endpoint bereitstellen, der ein vom Client in Form einer Zip-Datei (bestehend aus voud- und xml-Datei) geliefertes Test-Unit verarbeitet und in der DB ablegt.

**Comment by mechtelm** [comment]
Die Angaben der Import-XML zu Editor und Player sollen nicht geprüft werden. Wenn eines oder beide leer sind, dann bleiben auch in der Datenbank diese Felder leer. Das Frontend kann damit umgehen.

**Comment by mechtelm** [comment]
Wenn einer der Datei-Uploads fehlschlägt, gibt es eine Meldung in der Upload-Liste. Wenn die anschließende Verarbeitung Fehler hat - auch teilweise - sollte ein informativer Bericht erscheinen. Am besten wäre es evtl. das unter der Upload-Liste zu platzieren.
