### ISSUE TITLE
Wenn das Hochladen eines UnitPlayers fehlschlägt gibt es keine verständliche Fehlermeldung

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/teststudio-lite-backend#3]
Und die eigentliche Fehlermeldung wird verschluckt

- Z. 73 das else muss weg
- error code 401 im Fall vom fehlendem folder macht keinen Sinn (Z. 33)

gilt für
- php_superadmin/uploadItemPlayerFile.php
- und auch: php_superadmin/addItemAuthoringTool.php

**Comment by mechtelm** [comment]
Wegen der Neufassung in Version 2 (Studio-Lite) nicht mehr relevant.
