### ISSUE TITLE
Durcheinander mit Itemplayer/Authoring Tool Versionen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/teststudio-lite-backend#4]
In der DB wird nur die major version des itemplayers (z. B. 'IQBVisualUnitPlayerV2') zu einem Item abgelegt (kommt das so aus dem authoring tool?), die Files heißen aber nach der Minor-Version (z. B. 'IQBVisualUnitPlayerV2.1.0.html') und können dann nicht gefunden werden, z. B. hier: `vo_code/ItemAuthoringToolsFactory.php` Z. 386.

**Comment by mechtelm** [comment]
Wegen der Neufassung in Version 2 (Studio-Lite) nicht mehr relevant.
